### PR TITLE
add Shared Document Editing && User Presence Indicators.

### PR DESCRIPTION
**Pull request by chiefkarim**
Useful resources I found.
Next js 14:
[Migrating the old-style file router to the app router](https://www.youtube.com/watch?v=YQMSietiFm0)
[Migrating from API routes to server actions](https://www.youtube.com/watch?v=RadgkoJrhu0)

LiveBlocks:
[How to use Live blocks with Next.js /app directory](https://liveblocks.io/docs/guides/how-to-use-liveblocks-with-nextjs-app-directory)

[live preview](https://hiring-software-engineer-frontend.vercel.app/)

PS: i didn't use the starter kit. to get a better understanding of liveblocks.
thanks for the advice @strlrd-29 & @1hachem next js was easier than what I thought.

### CODE REVIEW

**Comment by strlrd-29** [comment]
Great! just make sure to add steps on running the project locally and all env vars needed.

**Comment by chiefkarim** [comment]
I just added the authentication part. maybe tomorrow I will finish the authorization.
- changed the readme file a little to show how to use authentication and what resources to refer to.
- used SSR package instead of helpers since Supabase recommends that (quoting `because they abstracted some unnecessary things we had to do with helpers package`)
- changed the UI a little to make it more friendly ^-^

**Comment by strlrd-29** [comment]
Great! I will check out you work.

**Comment by chiefkarim** [comment]
note currently am using server-side sessions for auth. this is acceptable since the project is running on one server or instance of the server but if the project is running on multiple servers or instances. we need to change to client-side cookies or other alternatives to keep all servers in sync.

**Comment by strlrd-29** [comment]
Some notes:
- In the home page it would be better if the sign in and sign up buttons only show if not logged in.
- Also for now when clicking on demo it automatically creates a room and opens it, but a better user experience would be to have the previous documents stored and users can open them and find their old changes.
- In the document page, there is overflow on the y axis. not centering the editor and giving it more height would be better.

**Comment by chiefkarim** [comment]
i will make these adjustments thank you for the detailed feedback.
for not showing the login when logged in can you show me how to reproduce the problem? because as you can see in the screenshot it's showing me only the log-out button when loged in.

**Comment by strlrd-29** [comment]
Yep the logout button only shows up if you are in the document page, but in the home page it always show the sign in and sign up buttons

**Comment by chiefkarim** [comment]
Screenshot 2023-12-25 at 11 01 19 AM
this is the homepge

**Comment by strlrd-29** [comment]
I just figured it out, it was because I didn't follow up with the email that get sent. It is working now.

**Comment by chiefkarim** [comment]
> I just figured it out, it was because I didn't follow up with the email that get sent. It is working now.

I will make sure to disable that from Supabase. For easier testing.
Thank you for the detailed feedback 🚀

**Comment by strlrd-29** [comment]
@chiefkarim We really appreciate the work that you have done, and for that we will be inviting you for an interview this week Inchallah, You will be contacted by our HR manager for the specefic details.

**Pull request closed without merging**
