### PR TITLE
Selma/supabase-auth-nextjs

### PR DESCRIPTION
**Pull request by SelmaMani**

### CODE REVIEW

**Comment by strlrd-29** [comment]
Thanks Selma for contributing, Can you add the steps to setting up the project (env variables, useful links, etc...).
- Also please add a .gitignore file to remove the DS_STORE files.

Thanks again for contributing and keep it up, consider working on the collaborative aspect of the app.

**Comment by SelmaMani** [comment]
Adding the steps to the readme file, can you please explain more which links i need to include

**Comment by strlrd-29** [comment]
For example you can add links for supabase on how to get the environment variables required for the app to run.

**Comment by SelmaMani** [comment]
Here is the documentation of using supabase with nextjs:
[](https://supabase.com/docs/guides/getting-started/quickstarts/nextjs)
basically you cannot get the env variables unless you are a memeber of the organization of that project in supabase, if you have a supabase account please share with me your email to give you access to the project and this way you can get the env variables from supabase or you can use them directly i just included them in the readme file ( an unsecure way to do it but since the project is just about authentication then no worries)

**Comment by strlrd-29** [comment]
No worries, thank you. I have already configured supabase correctly and got the correct env vars, what I meant is to add the steps in the README so that when we merge your work, people that will come after you will have clear instructions on how to run the project.

**Comment by SelmaMani** [comment]
I will consider adding useful resources in the README file.
Thank you for the feedback sir.

**Comment by strlrd-29** [comment]
@SelmaMani since there has been no more changes in the last week, I will be closing this pull request and merging some stuff from it to the main branch. Inchallah we will invite you over for an interview this week. You will be contacted in the upcoming days for the specefic details.

**Pull request closed without merging**
